name: Java CI with Maven

on:
  push:
    branches:
      - master  # O sostituisci con 'main' se il tuo branch principale si chiama 'main'
  pull_request:
    branches:
      - master  # O sostituisci con 'main' se il tuo branch principale si chiama 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [17]  # Usa OpenJDK 17

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adoptopenjdk'  # Puoi anche usare 'zulu' o 'openjdk'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install -DskipTests  # Se vuoi eseguire i test, rimuovi '-DskipTests'

      - name: Run tests
        run: mvn test  # Opzionale: puoi eseguire i test separatamente
